In [2]:
#importing necessary libraries
import pandas as pd
import numpy as np

In [6]:
#importing the csv file and showing the dataset
df = pd.read_csv("hero.csv", low_memory=False)
df

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,32310363,12/31/2015 11:59:45 PM,01-01-16 0:55,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10034.0,71 VERMILYEA AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.865682,-73.923501,"(40.86568153633767, -73.92350095571744)"
1,32309934,12/31/2015 11:59:44 PM,01-01-16 1:26,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11105.0,27-07 23 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.775945,-73.915094,"(40.775945312321085, -73.91509393898605)"
2,32309159,12/31/2015 11:59:29 PM,01-01-16 4:51,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,10458.0,2897 VALENTINE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.870325,-73.888525,"(40.870324522111424, -73.88852464418646)"
3,32305098,12/31/2015 11:57:46 PM,01-01-16 7:43,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,Street/Sidewalk,10461.0,2940 BAISLEY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.835994,-73.828379,"(40.83599404683083, -73.82837939584206)"
4,32306529,12/31/2015 11:56:58 PM,01-01-16 3:24,NYPD,New York City Police Department,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11373.0,87-14 57 ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.733060,-73.874170,"(40.733059618956815, -73.87416975810375)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300693,30281872,03/29/2015 12:33:41 AM,NaN,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,NaN,CRESCENT AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300694,30281230,03/29/2015 12:33:28 AM,03/29/2015 02:33:59 AM,NYPD,New York City Police Department,Blocked Driveway,Partial Access,Street/Sidewalk,11418.0,100-17 87 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.694077,-73.846087,"(40.69407728322387, -73.8460866160573)"
300695,30283424,03/29/2015 12:33:03 AM,03/29/2015 03:40:20 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,11206.0,162 THROOP AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.699590,-73.944234,"(40.69959035300927, -73.94423377144169)"
300696,30280004,03/29/2015 12:33:02 AM,03/29/2015 04:38:35 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10461.0,3151 EAST TREMONT AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.837708,-73.834587,"(40.8377075854206, -73.83458731019586)"
300697,30281825,03/29/2015 12:33:01 AM,03/29/2015 04:41:50 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,10036.0,251 WEST 48 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.760583,-73.985922,"(40.76058322950115, -73.98592204392392)"

In [7]:
#basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300698 entries, 0 to 300697
Data columns (total 53 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Unique Key                      300698 non-null  int64
 1   Created Date                    300698 non-null  object
 2   Closed Date                     298534 non-null  object
 3   Agency                          300698 non-null  object
 4   Agency Name                     300698 non-null  object
 5   Complaint Type                  300698 non-null  object
 6   Descriptor                      294784 non-null  object
 7   Location Type                   300567 non-null  object
 8   Incident Zip                    298083 non-null  float64
 9   Incident Address                256288 non-null  object
 10  Street Name                     256288 non-null  object
 11  Cross Street 1                  251419 non-null  object
 12  Cross Street 2                  250919 non-null  object
 13  Intersection Street 1           43858 non-null   object
 14  Intersection Street 2           43362 non-null   object
 15  Address Type                    297883 non-null  object
 16  City                            298084 non-null  object
 17  Landmark                        349 non-null     object
 18  Facility Type                   298527 non-null  object
 19  Status                          300698 non-null  object
 20  Due Date                        300695 non-null  object
 21  Resolution Description          300698 non-null  object
 22  Resolution Action Updated Date  298511 non-null  object
 23  Community Board                 300698 non-null  object
 24  Borough                         300698 non-null  object
 25  X Coordinate (State Plane)      297158 non-null  float64
 26  Y Coordinate (State Plane)      297158 non-null  float64
 27  Park Facility Name              300698 non-null  object
 28  Park Borough                    300698 non-null  object
 29  School Name                     300698 non-null  object
 30  School Number                   300698 non-null  object
 31  School Region                   300697 non-null  object
 32  School Code                     300697 non-null  object
 33  School Phone Number             300698 non-null  object
 34  School Address                  300698 non-null  object
 35  School City                     300698 non-null  object
 36  School State                    300698 non-null  object
 37  School Zip                      300697 non-null  object
 38  School Not Found                300698 non-null  object
 39  School or Citywide Complaint    0 non-null       float64
 40  Vehicle Type                    0 non-null       float64
 41  Taxi Company Borough            0 non-null       float64
 42  Taxi Pick Up Location           0 non-null       float64
 43  Bridge Highway Name             243 non-null     object
 44  Bridge Highway Direction        243 non-null     object
 45  Road Ramp                       213 non-null     object
 46  Bridge Highway Segment          213 non-null     object
 47  Garage Lot Name                 0 non-null       float64
 48  Ferry Direction                 1 non-null       object
 49  Ferry Terminal Name             2 non-null       object
 50  Latitude                        297158 non-null  float64
 51  Longitude                       297158 non-null  float64
 52  Location                        297158 non-null  object
dtypes: float64(10), int64(1), object(42)
memory usage: 121.6+ MB

In [8]:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300698 entries, 0 to 300697
Data columns (total 53 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   Unique Key                      300698 non-null  int64  
 1   Created Date                    300698 non-null  object 
 2   Closed Date                     298534 non-null  object 
 3   Agency                          300698 non-null  object 
 4   Agency Name                     300698 non-null  object 
 5   Complaint Type                  300698 non-null  object 
 6   Descriptor                      294784 non-null  object 
 7   Location Type                   300567 non-null  object 
 8   Incident Zip                    298083 non-null  float64
 9   Incident Address                256288 non-null  object 
 10  Street Name                     256288 non-null  object 
 11  Cross Street 1                  251419 non-null  object 
 12  Cross Street 2                  250919 non-null  object 
 13  Intersection Street 1           43858 non-null   object 
 14  Intersection Street 2           43362 non-null   object 
 15  Address Type                    297883 non-null  object 
 16  City                            298084 non-null  object 
 17  Landmark                        349 non-null     object 
 18  Facility Type                   298527 non-null  object 
 19  Status                          300698 non-null  object 
 20  Due Date                        300695 non-null  object 
 21  Resolution Description          300698 non-null  object 
 22  Resolution Action Updated Date  298511 non-null  object 
 23  Community Board                 300698 non-null  object 
 24  Borough                         300698 non-null  object 
 25  X Coordinate (State Plane)      297158 non-null  float64
 26  Y Coordinate (State Plane)      297158 non-null  float64
 27  Park Facility Name              300698 non-null  object 
 28  Park Borough                    300698 non-null  object 
 29  School Name                     300698 non-null  object 
 30  School Number                   300698 non-null  object 
 31  School Region                   300697 non-null  object 
 32  School Code                     300697 non-null  object 
 33  School Phone Number             300698 non-null  object 
 34  School Address                  300698 non-null  object 
 35  School City                     300698 non-null  object 
 36  School State                    300698 non-null  object 
 37  School Zip                      300697 non-null  object 
 38  School Not Found                300698 non-null  object 
 39  School or Citywide Complaint    0 non-null       float64
 40  Vehicle Type                    0 non-null       float64
 41  Taxi Company Borough            0 non-null       float64
 42  Taxi Pick Up Location           0 non-null       float64
 43  Bridge Highway Name             243 non-null     object 
 44  Bridge Highway Direction        243 non-null     object 
 45  Road Ramp                       213 non-null     object 
 46  Bridge Highway Segment          213 non-null     object 
 47  Garage Lot Name                 0 non-null       float64
 48  Ferry Direction                 1 non-null       object 
 49  Ferry Terminal Name             2 non-null       object 
 50  Latitude                        297158 non-null  float64
 51  Longitude                       297158 non-null  float64
 52  Location                        297158 non-null  object 
dtypes: float64(10), int64(1), object(42)
memory usage: 121.6+ MB

SyntaxError: invalid syntax (307321751.py, line 1)

In [9]:
#showing all the columns in the dataset
df.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Description', 'Resolution Action Updated Date',
       'Community Board', 'Borough', 'X Coordinate (State Plane)',
       'Y Coordinate (State Plane)', 'Park Facility Name', 'Park Borough',
       'School Name', 'School Number', 'School Region', 'School Code',
       'School Phone Number', 'School Address', 'School City', 'School State',
       'School Zip', 'School Not Found', 'School or Citywide Complaint',
       'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location',
       'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp',
       'Bridge Highway Segment', 'Garage Lot Name', 'Ferry Direction',
       'Ferry Terminal Name', 'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [ ]:
Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Description', 'Resolution Action Updated Date',
       'Community Board', 'Borough', 'X Coordinate (State Plane)',
       'Y Coordinate (State Plane)', 'Park Facility Name', 'Park Borough',
       'School Name', 'School Number', 'School Region', 'School Code',
       'School Phone Number', 'School Address', 'School City', 'School State',
       'School Zip', 'School Not Found', 'School or Citywide Complaint',
       'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location',
       'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp',
       'Bridge Highway Segment', 'Garage Lot Name', 'Ferry Direction',
       'Ferry Terminal Name', 'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [ ]:
# Convert "Created Date" and "Closed Date" to datetime datat_ype 
df['Created Date'] = pd.to_datetime(df['Created Date']);
df['Closed Date'] = pd.to_datetime(df['Closed Date']);

In [ ]:
#showing datatypes of wach colomns
df.dtypes

In [ ]:
Unique Key                                 int64
Created Date                      datetime64[ns]
Closed Date                       datetime64[ns]
Agency                                    object
Agency Name                               object
Complaint Type                            object
Descriptor                                object
Location Type                             object
Incident Zip                             float64
Incident Address                          object
Street Name                               object
Cross Street 1                            object
Cross Street 2                            object
Intersection Street 1                     object
Intersection Street 2                     object
Address Type                              object
City                                      object
Landmark                                  object
Facility Type                             object
Status                                    object
Due Date                                  object
Resolution Description                    object
Resolution Action Updated Date            object
Community Board                           object
Borough                                   object
X Coordinate (State Plane)               float64
Y Coordinate (State Plane)               float64
Park Facility Name                        object
Park Borough                              object
School Name                               object
School Number                             object
School Region                             object
School Code                               object
School Phone Number                       object
School Address                            object
School City                               object
School State                              object
School Zip                                object
School Not Found                          object
School or Citywide Complaint             float64
Vehicle Type                             float64
Taxi Company Borough                     float64
Taxi Pick Up Location                    float64
Bridge Highway Name                       object
Bridge Highway Direction                  object
Road Ramp                                 object
Bridge Highway Segment                    object
Garage Lot Name                          float64
Ferry Direction                           object
Ferry Terminal Name                       object
Latitude                                 float64
Longitude                                float64
Location                                  object
dtype: object

In [ ]:
#creating a new column to store as the time elapsed between request creation and request closing in seconds
df['Request_Closing_Time'] = (df['Closed Date'] - df['Created Date']).dt.total_seconds()
df[['Request_Closing_Time']].head() #showing updated dataframe

In [ ]:
#dropping irrelevent coloumns from dataset according ot the quesion
df = df.drop(columns=['Agency Name','Incident Address','Street Name','Cross Street 1','Cross Street 2','Intersection Street 1', 
                      'Intersection Street 2','Address Type','Park Facility Name','Park Borough','School Name', 'School Number',
                      'School Region','School Code','School Phone Number','School Address','School City', 'School State','School Zip',
                      'School Not Found','School or Citywide Complaint','Vehicle Type', 'Taxi Company Borough','Taxi Pick Up Location',
                      'Bridge Highway Name','Bridge Highway Direction','Road Ramp','Bridge Highway Segment',
                      'Garage Lot Name','Ferry Direction','Ferry Terminal Name','Landmark','X Coordinate (State Plane)','Y Coordinate (State Plane)',
                      'Due Date','Resolution Action Updated Date','Community Board','Facility Type','Location'])
df.info()

In [ ]:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300698 entries, 0 to 300697
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype         
---  ------                  --------------   -----         
 0   Unique Key              300698 non-null  int64         
 1   Created Date            300698 non-null  datetime64[ns]
 2   Closed Date             298534 non-null  datetime64[ns]
 3   Agency                  300698 non-null  object        
 4   Complaint Type          300698 non-null  object        
 5   Descriptor              294784 non-null  object        
 6   Location Type           300567 non-null  object        
 7   Incident Zip            298083 non-null  float64       
 8   City                    298084 non-null  object        
 9   Status                  300698 non-null  object        
 10  Resolution Description  300698 non-null  object        
 11  Borough                 300698 non-null  object        
 12  Latitude                297158 non-null  float64       
 13  Longitude               297158 non-null  float64       
 14  Request_Closing_Time    298534 non-null  float64       
dtypes: datetime64[ns](2), float64(4), int64(1), object(8)
memory usage: 34.4+ MB

In [ ]:
#checking if any missing values or not
df.isnull()

In [ ]:
#showing the number of missing values in each column
df.isnull().sum()

In [ ]:
Unique Key                   0
Created Date                 0
Closed Date               2164
Agency                       0
Complaint Type               0
Descriptor                5914
Location Type              131
Incident Zip              2615
City                      2614
Status                       0
Resolution Description       0
Borough                      0
Latitude                  3540
Longitude                 3540
Request_Closing_Time      2164
dtype: int64

In [ ]:
#removing all the missing values or naan values from updated dataframe
df = df.dropna()
df.describe()

In [ ]:
#showing number unique values for every columns
df.nunique()

In [ ]:
Unique Key                291107
Created Date              251970
Closed Date               231991
Agency                         1
Complaint Type                15
Descriptor                    41
Location Type                 14
Incident Zip                 200
City                          53
Status                         1
Resolution Description        12
Borough                        5
Latitude                  123013
Longitude                 123112
Request_Closing_Time       47134
dtype: int64

In [ ]:
# showing first 5 unique values for each column
for column in df.columns:
    print(f"First 3 unique values in '{column}':")
    print(df[column].unique()[:3])# Only take the first 53
    print("-" )

In [ ]:
First 3 unique values in 'Unique Key':
[32310363 32309934 32309159]
-
First 3 unique values in 'Created Date':
<DatetimeArray>
['2015-12-31 23:59:45', '2015-12-31 23:59:44', '2015-12-31 23:59:29']
Length: 3, dtype: datetime64[ns]
-
First 3 unique values in 'Closed Date':
<DatetimeArray>
['2016-01-01 00:55:00', '2016-01-01 01:26:00', '2016-01-01 04:51:00']
Length: 3, dtype: datetime64[ns]
-
First 3 unique values in 'Agency':
['NYPD']
-
First 3 unique values in 'Complaint Type':
['Noise - Street/Sidewalk' 'Blocked Driveway' 'Illegal Parking']
-
First 3 unique values in 'Descriptor':
['Loud Music/Party' 'No Access' 'Commercial Overnight Parking']
-
First 3 unique values in 'Location Type':
['Street/Sidewalk' 'Club/Bar/Restaurant' 'Store/Commercial']
-
First 3 unique values in 'Incident Zip':
[10034. 11105. 10458.]
-
First 3 unique values in 'City':
['NEW YORK' 'ASTORIA' 'BRONX']
-
First 3 unique values in 'Status':
['Closed']
-
First 3 unique values in 'Resolution Description':
['The Police Department responded and upon arrival those responsible for the condition were gone.'
 'The Police Department responded to the complaint and with the information available observed no evidence of the violation at that time.'
 'The Police Department responded to the complaint and took action to fix the condition.']
-
First 3 unique values in 'Borough':
['MANHATTAN' 'QUEENS' 'BRONX']
-
First 3 unique values in 'Latitude':
[40.86568154 40.77594531 40.87032452]
-
First 3 unique values in 'Longitude':
[-73.92350096 -73.91509394 -73.88852464]
-
First 3 unique values in 'Request_Closing_Time':
[ 3315.  5176. 17491.]
-

In [ ]:
 #to get the summary statistics of 'latitude'
col = 'Latitude'
summary = df[col].describe()
summary

In [ ]:
count    291107.000000
mean         40.725681
std           0.082411
min          40.499135
25%          40.668926
50%          40.717782
75%          40.782973
max          40.912869
Name: Latitude, dtype: float64

In [ ]:
#Calculate and show the sum of the Latitude
total_sum = df[col].sum()
f" Total Sum: {total_sum} "

In [ ]:
' Total Sum: 11855530.75877829 '

In [ ]:
#Calculate and show the mean of the Latitude
mean = df[col].mean()
f" Mean: {mean} "

In [ ]:
' Mean: 40.72568079358549 '

In [ ]:
#Calculate and show the standard deviation of the Latitude 
stan_dev = df[col].std()
f" Standard Deviation: {stan_dev:.3f} "

In [ ]:
' Standard Deviation: 0.082 '

In [ ]:
# Calculate skewness of the column and display formatted result
skewness = df[col].skew()
f" skewness: {skewness:.3f} "

In [ ]:
' skewness: 0.123 '

In [ ]:
# Calculate kurtosis of the column and display formatted result
kurtosis = df[col].kurt()
f" kurtosis: {kurtosis:.3f} "

In [ ]:
' kurtosis: -0.735 '

In [ ]:
#to see most common compaint types in bar graph
import matplotlib.pyplot as plt
top_complaints = df['Complaint Type'].value_counts().head(5)

plt.figure(figsize=(10, 6))
top_complaints.plot(kind='bar', color='red')
plt.title(' Most Common Complaint Types')
plt.xlabel('Complaint Type')
plt.ylabel('Number of Complaints')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

In [ ]:
# Calculate correlations between numeric columns
correlations = df.select_dtypes(include=['number'])#selecting only numerical columns
corr= correlations.corr()

print("Correlation Matrix:")
corr

In [ ]:
Correlation Matrix:

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))  # Set the size of the plot
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title("Heatmap of Correlation Matrix")
plt.show()

In [ ]:
#Number of complain by borough
no_borough = df['Borough'].value_counts()

plt.figure(figsize=(8,5))
no_borough.plot(kind='barh', color='coral')  
plt.title('Number of Complaints by Borough')
plt.xlabel('Total Complaints')
plt.ylabel('Borough')
plt.tight_layout()
plt.show()

In [ ]:
#seeing monyhly complaints trends
df['Month'] = df['Created Date'].dt.month
monthly_df = df['Month'].value_counts().sort_index()  #checking number of complaints occurs every month

plt.figure(figsize=(10,6))
monthly_df.plot(kind='line', marker='*', color='black')
plt.title('Monthly Trends')
plt.xlabel('Month (1 = Jan, 30 = Dec)')
plt.ylabel('Number of Complaints')
plt.grid(True)
plt.tight_layout()
plt.show()

In [ ]:
#Number of complain in top 5 cities
recent_locat = df['City'].value_counts().head(5).index
new_data = df[df['City'].isin(recent_locat)]

#Count the number of complaints by city
complaints_by_city = new_data['City'].value_counts()

import seaborn as sns
plt.figure(figsize=(8,8))
plt.pie(complaints_by_city, labels=complaints_by_city.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette("Set3", len(complaints_by_city)))
plt.title('Distribution of Complaints in Cities')
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.tight_layout()
plt.show()

In [ ]:
#Arrange the complaint types according to their average
#calculating average request closing time by complaint types and borough
avg_closing_time = df.groupby(['Complaint Type', 'Location Type'])['Request_Closing_Time'].mean().reset_index()
avg_closing_time['Request_Closing_Hours'] = avg_closing_time['Request_Closing_Time'] / 3600  #converting time into hours

#pivot table
pivot_table = avg_closing_time.pivot(index='Complaint Type', columns='Location Type', values='Request_Closing_Hours')
pivot_table

In [ ]:
#plotting in graph
pivot_table.plot(kind='bar', figsize=(12, 7),width=1.85)
plt.title('Average Request Closing Time (hours) by Complaint Type and Location')
plt.ylabel('Average Closing Time (Hours)')
plt.xlabel('Complaint Type')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

In [ ]:
#testing whether the average respnse time across complaint types is similar or not
new_df = df.dropna(subset=['Complaint Type', 'Request_Closing_Time']) #ensuring missing values are handled

top_complaints = new_df ['Complaint Type'].value_counts().head(5).index 
ranfil = new_df[new_df['Complaint Type'].isin(top_complaints)]

ranfil.head()

In [ ]:
#preparing for anova testing
grouped = ranfil.groupby('Complaint Type')
groups = [group['Request_Closing_Time'].dropna() for _, group in grouped]
group_names = list(grouped.groups.keys())

#converting time into hours for all the groups
groups_in_hours = [group / 3600 for group in groups]

In [ ]:
import scipy.stats as stats

f_stat, p_value = stats.f_oneway(*groups_in_hours)

In [ ]:
# Display the results
print(f"\nANOVA Test Results:")
print("F-statistic:", f_stat)
print("P-value:", p_value)

In [ ]:

ANOVA Test Results:
F-statistic: 1789.8124885501425
P-value: 0.0

In [ ]:
#testing whether the complaint type and location type are related
#Perform Chi-Square Test of Independence
from scipy.stats import chi2_contingency
top_complaints = new_df ['Complaint Type'].value_counts().head(10).index
latest_df = new_df [new_df ['Complaint Type'].isin(top_complaints)].dropna(subset=['Location Type'])

#creating a contingency table
contingency_table = pd.crosstab(latest_df['Complaint Type'], latest_df['Location Type'])

In [ ]:
#displaying the results
chi2, p_value, dof, expected = stats.chi2_contingency(contingency_table)
print(f"\nChi-Square Test Results:")
print("Chi-square Statistic:", chi2)
print("P-value:", p_value)
print("Degrees of Freedpm:", dof)

In [ ]:

Chi-Square Test Results:
Chi-square Statistic: 766955.9360776196
P-value: 0.0
Degrees of Freedpm: 108